import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script src="https://www.paypal.com/sdk/js?client-id=AY5XsZSGSHSaMKiLuIfFysPQSZL-u9Z9puU5Tj84H_dGkC8MXqs-PyzcSKg5zySF21FGiNc8K9bmCXi6&currency=USD"></Script>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
